SHELTERLUV_CAT_BREED_MAPPING = {
    "Abyssinian": "Abyssinian",
    "American Bobtail": "American Bobtail",
    "American Curl": "American Curl",
    "American Shorthair": "American Shorthair",
    "American Wirehair": "American Wirehair",
    "Balinese": "Balinese",
    "Bengal": "Bengal",
    "Birman": "Birman",
    "Bombay": "Bombay",
    "British Shorthair": "British Shorthair",
    "Burmese": "Burmese",
    "Chartreux": "Chartreux",
    "Colorpoint Shorthair": "Siamese",
    "Cornish Rex": "Cornish Rex",
    "Cymric": "Cymric",
    "Devon Rex": "Devon Rex",
    "Domestic Longhair": "Domestic Long Hair",
    "Domestic Medium Hair": "Domestic Medium Hair",
    "Domestic Shorthair": "Domestic Short Hair",
    "Egyptian Mau": "Egyptian Mau",
    "Exotic Longhair": "Domestic Long Hair",
    "Exotic Shorthair": "Domestic Shorthair",
    "Extra-Toes Cat (Hemingway Polydactyl)": "Extra-Toes Cat / Hemingway Polydactyl",
    "Havana Brown": "Havana",
    "Himalayan": "Himalayan",
    "Japanese Bobtail": "Japanese Bobtail",
    "Javanese": "Javanese",
    "Korat": "Korat",
    "Laperm": "LaPerm",
    "Maine Coon": "Maine Coon",
    "Manx": "Manx",
    "Munchkin": "Munchkin",
    "Nebelung": "Nebelung",
    "Norwegian Forest Cat": "Norwegian Forest Cat",
    "Ocicat": "Ocicat",
    "Oriental Long Hair": "Oriental Long Hair",
    "Oriental Short Hair": "Oriental Short Hair",
    "Persian": "Persian",
    "Pixie-Bob": "Pixiebob",
    "Ragamuffin": "Ragamuffin",
    "Ragdoll": "Ragdoll",
    "Russian Blue": "Russian Blue",
    "Scottish Fold": "Scottish Fold",
    "Selkirk Rex": "Selkirk Rex",
    "Siamese": "Siamese",
    "Siberian": "Siberian",
    "Singapura": "Singapura",
    "Snowshoe": "Snowshoe",
    "Somali": "Somali",
    "Sphynx": "Sphynx / Hairless Cat",
    "Tonkinese": "Tonkinese",
    "Turkish Angora": "Turkish Angora",
    "Turkish Van": "Turkish Van",
    "Unknown": "Domestic Short Hair",
}

SHELTERLUV_CAT_COLOR_MAPPING = {
    "Albino": "White",
    "Apricot": "Buff / Tan / Fawn",
    "Black": "Black",
    "Blonde": "Buff / Tan / Fawn",
    "Blue Black": "Black",
    "Blue": "Gray / Blue / Silver",
    "Brown": "Brown / Chocolate",
    "Buff": "Buff / Tan / Fawn",
    "Calico": "Calico",
    "Charcoal": "Gray / Blue / Silver",
    "Chocolate": "Brown / Chocolate",
    "Copper": "Orange / Red",
    "Cream": "Cream / Ivory",
    "Ebony": "Black",
    "Fawn": "Buff / Tan / Fawn",
    "Flame": "Flame Point",
    "Grey": "Gray / Blue / Silver",
    "Lilac": "Lilac Point",
    "Liver": "Brown / Chocolate",
    "Lynx": "Gray / Blue / Silver",
    "Mahogany": "Brown / Chocolate",
    "Orange": "Orange / Red",
    "Red": "Orange / Red",
    "Ruddy": "Brown / Chocolate",
    "Rust": "Brown / Chocolate",
    "Sable": "Brown / Chocolate",
    "Salt & Pepper": "Gray / Blue / Silver",
    "Seal": "Seal Point",
    "Shaded Blue Cream Cameo": "Blue Cream",
    "Silver Black": "Gray / Blue / Silver",
    "Silver": "Gray / Blue / Silver",
    "Smoke": "Smoke",
    "Tan": "Buff / Tan / Fawn",
    "Torbie": "Torbie",
    "Tortoise": "Tortoiseshell",
    "Wheaten": "Buff / Tan / Fawn",
    "White": "White",
    "Yellow": "Orange / Red",
}

SHELTERLUV_DOG_BREED_MAPPING = {
    "Affenpinscher": "Affenpinscher",
    "Akbash": "Akbash",
    "Akita": "Akita",
    "American Blue Heeler": "Australian Cattle Dog / Blue Heeler",
    "Appenzell Mountain Dog": "Appenzell Mountain Dog",
    "Basenji": "Basenji",
    "Beagle": "Beagle",
    "Beauceron": "Beauceron",
    "Berger Picard": "Shepherd",
    "Bernese Mountain Dog": "Bernese Mountain Dog",
    "Bichon Frise": "Bichon Frise",
    "Black Mouth Cur": "Black Mouth Cur",
    "Bloodhound": "Bloodhound",
    "Blue Lacy": "Blue Lacy",
    "Boerboel": "Boerboel",
    "Bolognese": "Bolognese",
    "Borzoi": "Borzoi",
    "Boxer": "Boxer",
    "Brasileiro, Fila": "Fila Brasileiro",
    "Briard": "Briard",
    "Buhund, Norwegian": "Norwegian Buhund",
    "Bulldog": "American Bulldog",
    "Bulldog, American": "American Bulldog",
    "Bulldog, English": "English Bulldog",
    "Bulldog, French": "French Bulldog",
    "Bulldog, Old English": "English Bulldog",
    "Bulldog, Victorian": "English Bulldog",
    "Bullmastiff": "Bullmastiff",
    "Canaan Dog": "Canaan Dog",
    "Canario, Presa": "Presa Canario",
    "Carolina Dog": "Carolina Dog",
    "Catahoula Leopard Dog": "Catahoula Leopard Dog",
    "Cattle Dog": "Cattle Dog",
    "Cattle Dog, Australian (Blue Heeler)": "Australian Cattle Dog / Blue Heeler",
    "Cattle Dog, Australian (Red Heeler)": "Cattle Dog",
    "Chihuahua": "Chihuahua",
    "Chihuahua, Long Coat": "Chihuahua",
    "Chihuahua, Short Coat": "Chihuahua",
    "Chinese Crested Dog": "Chinese Crested Dog",
    "Chinese Shar-Pei": "Shar-Pei",
    "Chow Chow": "Chow Chow",
    "Cockapoo": "Cockapoo",
    "Collie": "Collie",
    "Collie, Bearded": "Bearded Collie",
    "Collie, Border": "Border Collie",
    "Collie, Rough": "Rough Collie",
    "Collie, Smooth": "Smooth Collie",
    "Coonhound": "Coonhound",
    "Coonhound, Bluetick": "Bluetick Coonhound",
    "Coonhound, English": "English Coonhound",
    "Coonhound, Redbone": "Redbone Coonhound",
    "Coonhound, Treeing Walker": "Treeing Walker Coonhound",
    "Corgi, Cardigan Welsh": "Cardigan Welsh Corgi",
    "Corgi, Pembroke Welsh": "Pembroke Welsh Corgi",
    "Coton De Tulear": "Coton de Tulear",
    "Dachshund": "Dachshund",
    "Dachshund, Miniature Long Haired": "Miniature Dachshund",
    "Dachshund, Miniature Smooth Haired": "Miniature Dachshund",
    "Dachshund, Miniature Wire Haired": "Miniature Dachshund",
    "Dachshund, Standard Long Haired": "Dachshund",
    "Dachshund, Standard Smooth Haired": "Dachshund",
    "Dachshund, Standard Wire Haired": "Wirehaired Dachshund",
    "Dalmatian": "Dalmatian",
    "Dogo Argentino": "Dogo Argentino",
    "Dogue de Bordeaux": "Dogue de Bordeaux",
    "Elkhound, Norwegian": "Norwegian Elkhound",
    "Entlebucher": "Entlebucher",
    "Eskimo Dog": "Eskimo Dog",
    "Eskimo, American": "American Eskimo Dog",
    "Feist": "Feist",
    "Flanders, Bouvier Des": "Bouvier des Flandres",
    "Foxhound, American": "American Foxhound",
    "Foxhound, English": "English Foxhound",
    "Great Dane": "Great Dane",
    "Greater Swiss Mountain Dog": "Greater Swiss Mountain Dog",
    "Greyhound": "Greyhound",
    "Greyhound, Italian": "Italian Greyhound",
    "Griffon, Brussels": "Brussels Griffon",
    "Griffon, Petit Basset Vendeen": "Petit Basset Griffon Vendeen",
    "Griffon, Wire-Haired Pointing": "Wirehaired Pointing Griffon",
    "Havanese": "Havanese",
    "Hound": "Hound",
    "Hound, Afghan": "Afghan Hound",
    "Hound, Basset": "Basset Hound",
    "Hound, Black and Tan Coonhound": "Black and Tan Coonhound",
    "Hound, Bloodhound": "Bloodhound",
    "Hound, Halden (Haldenstover)": "Hound",
    "Hound, Ibizan": "Ibizan Hound",
    "Hound, Irish Wolfhound": "Irish Wolfhound",
    "Hound, Pharaoh": "Pharaoh Hound",
    "Hound, Plott": "Plott Hound",
    "Hound, Scottish Deerhound": "Scottish Deerhound",
    "Husky": "Husky",
    "Husky, Alaskan": "Husky",
    "Husky, Siberian": "Siberian Husky",
    "Japanese Chin": "Japanese Chin",
    "Kai Dog": "Kai Dog",
    "Karelian Bear Dog": "Karelian Bear Dog",
    "Keeshond": "Keeshond",
    "Kelpie, Australian": "Australian Kelpie",
    "Klee Kai": "Klee Kai",
    "Komondor": "Komondor",
    "Korean Jindo": "Jindo",
    "Kuvasz": "Kuvasz",
    "Lapphund, Finnish": "Finnish Lapphund",
    "Leonberger": "Leonberger",
    "Lhasa Apso": "Lhasa Apso",
    "Lowchen": "Lowchen",
    "Lundehund, Norwegian": "Norwegian Lundehund",
    "Malamute, Alaskan": "Alaskan Malamute",
    "Malinois, Belgian": "Belgian Shepherd / Malinois",
    "Maltese": "Maltese",
    "Mastiff": "Mastiff",
    "Mastiff, Bullmastiff": "Bullmastiff",
    "Mastiff, Cane Corso": "Cane Corso",
    "Mastiff, Neapolitan": "Neapolitan Mastiff",
    "Mastiff, Tibetan": "Tibetan Mastiff",
    "Mixed Breed (Large)": "Mixed Breed",
    "Mixed Breed (Medium)": "Mixed Breed",
    "Mixed Breed (Small)": "Mixed Breed",
    "Mountain Cur": "Mountain Cur",
    "Mountain Dog": "Mountain Dog",
    "Newfoundland": "Newfoundland Dog",
    "Norbottenspets": "Spitz",
    "Nureongi": "Jindo",
    "Otterhound": "Otterhound",
    "Papillon": "Papillon",
    "Pekingese": "Pekingese",
    "Pinscher, Austrian": "German Pinscher",
    "Pinscher, Doberman": "Doberman Pinscher",
    "Pinscher, German": "German Pinscher",
    "Pinscher, Miniature": "Miniature Pinscher",
    "Pointer": "Pointer",
    "Pointer, English": "English Pointer",
    "Pointer, German Shorthaired": "German Shorthaired Pointer",
    "Pointer, German Wirehaired": "German Wirehaired Pointer",
    "Pomeranian": "Pomeranian",
    "Poodle": "Poodle",
    "Poodle, Miniature": "Miniature Poodle",
    "Poodle, Standard": "Standard Poodle",
    "Poodle, Toy": "Poodle",
    "Portugese Water Dog": "Portugese Water Dog",
    "Pug": "Pug",
    "Puli": "Puli",
    "Pyrenees, Great": "Great Pyrenees",
    "Queensland Heeler": "Cattle Dog",
    "Retriever": "Retriever",
    "Retriever, Black Labrador": "Black Labrador Retriever",
    "Retriever, Chesapeake Bay": "Chesapeake Bay Retriever",
    "Retriever, Chocolate Labrador": "Chocolate Labrador Retriever",
    "Retriever, Curly-Coated": "Curly-Coated Retriever",
    "Retriever, Flat-Coated": "Flat-Coated Retriever",
    "Retriever, Golden": "Golden Retriever",
    "Retriever, Labrador": "Labrador Retriever",
    "Retriever, Nova Scotia Duck-Tolling": "Nova Scotia Duck Tolling Retriever",
    "Retriever, Yellow Labrador": "Yellow Labrador Retriever",
    "Ridgeback, Rhodesian": "Rhodesian Ridgeback",
    "Ridgeback, Thai": "Thai Ridgeback",
    "Rottweiler": "Rottweiler",
    "Saint Bernard": "Saint Bernard",
    "Saluki": "Saluki",
    "Samoyed": "Samoyed",
    "Schipperke": "Schipperke",
    "Schnauzer": "Schnauzer",
    "Schnauzer, Giant": "Giant Schnauzer",
    "Schnauzer, Miniature": "Miniature Schnauzer",
    "Schnauzer, Standard": "Standard Schnauzer",
    "Setter": "Setter",
    "Setter, English": "English Setter",
    "Setter, Gordon": "Gordon Setter",
    "Setter, Irish": "Irish Setter",
    "Sheep Dog": "Sheep Dog",
    "Sheepdog, Caucasian Ovtcharka": "Caucasian Sheepdog / Caucasian Ovtcharka",
    "Sheepdog, Mcnab": "McNab",
    "Sheepdog, Old English": "Old English Sheepdog",
    "Sheepdog, Polish Lowland": "Polish Lowland Sheepdog",
    "Sheepdog, Shetland": "Shetland Sheepdog / Sheltie",
    "Shepherd": "Shepherd",
    "Shepherd, Anatolian": "Anatolian Shepherd",
    "Shepherd, Australian": "Australian Shepherd",
    "Shepherd, Belgian Malinois": "Belgian Shepherd / Malinois",
    "Shepherd, Belgian Sheepdog": "Belgian Shepherd / Sheepdog",
    "Shepherd, Belgian Tervuren": "Belgian Shepherd / Tervuren",
    "Shepherd, Dutch": "Dutch Shepherd",
    "Shepherd, English": "English Shepherd",
    "Shepherd, German": "German Shepherd Dog",
    "Shepherd, German King": "German Shepherd Dog",
    "Shepherd, White German": "White German Shepherd",
    "Shiba Inu": "Shiba Inu",
    "Shih Tzu": "Shih Tzu",
    "Sloughi": "Sloughi",
    "Spaniel": "Spaniel",
    "Spaniel, American Cocker": "Cocker Spaniel",
    "Spaniel, American Water": "American Water Spaniel",
    "Spaniel, Brittany": "Brittany Spaniel",
    "Spaniel, Cavalier King Charles": "Cavalier King Charles Spaniel",
    "Spaniel, Clumber": "Clumber Spaniel",
    "Spaniel, Cocker": "Cocker Spaniel",
    "Spaniel, English Cocker": "Cocker Spaniel",
    "Spaniel, English Springer": "English Springer Spaniel",
    "Spaniel, English Toy": "English Toy Spaniel",
    "Spaniel, Irish Water": "Irish Water Spaniel",
    "Spaniel, Sussex": "Sussex Spaniel",
    "Spaniel, Tibetan": "Tibetan Spaniel",
    "Spaniel, Welsh Springer": "Welsh Springer Spaniel",
    "Spinone, Italian": "Spinone Italiano",
    "Spitz": "Spitz",
    "Spitz, Finnish": "Finnish Spitz",
    "Spitz, German": "German Spitz",
    "Taiwanese Mountain Dog": "Mountain Dog",
    "Terrier": "Terrier",
    "Terrier, Airedale": "Airedale Terrier",
    "Terrier, American Hairless": "American Hairless Terrier",
    "Terrier, American Pit Bull": "Pit Bull Terrier",
    "Terrier, American Staffordshire": "American Staffordshire Terrier",
    "Terrier, Australian": "Australian Terrier",
    "Terrier, Bedlington": "Bedlington Terrier",
    "Terrier, Black Russian": "Black Russian Terrier",
    "Terrier, Border": "Border Terrier",
    "Terrier, Boston": "Boston Terrier",
    "Terrier, Bull": "Bull Terrier",
    "Terrier, Cairn": "Cairn Terrier",
    "Terrier, Dandi Dinmont": "Dandie Dinmont Terrier",
    "Terrier, Fox": "Fox Terrier",
    "Terrier, Fox, Smooth": "Smooth Fox Terrier",
    "Terrier, Glen of Imaal": "Glen of Imaal Terrier",
    "Terrier, Irish": "Irish Terrier",
    "Terrier, Jack Russell": "Jack Russell Terrier",
    "Terrier, Kerry Blue": "Kerry Blue Terrier",
    "Terrier, Lakeland": "Lakeland Terrier",
    "Terrier, Manchester": "Manchester Terrier",
    "Terrier, Norfolk": "Norfolk Terrier",
    "Terrier, Norwich": "Norwich Terrier",
    "Terrier, Parson Jack Russell": "Parson Russell Terrier",
    "Terrier, Patterdale (Fell)": "Patterdale Terrier / Fell Terrier",
    "Terrier, Pit Bull": "Pit Bull Terrier",
    "Terrier, Rat": "Rat Terrier",
    "Terrier, Scottish Scottie": "Scottish Terrier",
    "Terrier, Sealyham": "Sealyham Terrier",
    "Terrier, Silky": "Silky Terrier",
    "Terrier, Skye": "Skye Terrier",
    "Terrier, Smooth Fox": "Smooth Fox Terrier",
    "Terrier, Soft Coated Wheaten": "Wheaten Terrier",
    "Terrier, Staffordshire Bull": "Staffordshire Bull Terrier",
    "Terrier, Tibetan": "Tibetan Terrier",
    "Terrier, Toy Fox": "Toy Fox Terrier",
    "Terrier, Welsh": "Welsh Terrier",
    "Terrier, West Highland White Westie": "West Highland White Terrier / Westie",
    "Terrier, Wheaten": "Wheaten Terrier",
    "Terrier, Wire Fox": "Wire Fox Terrier",
    "Terrier, Wirehaired": "Wirehaired Terrier",
    "Terrier, Yorkshire, Yorkie": "Yorkshire Terrier",
    "Unknown": "Mixed Breed",
    "Vallhund, Swedish": "Swedish Vallhund",
    "Vizsla": "Vizsla",
    "Vizsla, Smooth Haired": "Viszla",
    "Water Dog, Portuguese": "Portuguese Water Dog",
    "Weimaraner": "Weimaraner",
    "Whippet": "Whippet",
    "Wolfhound, Irish": "Irish Wolfhound",
    "Xoloitzcuintle (Mexican Hairless)": "Xoloitzcuintli / Mexican Hairless",
}

SHELTERLUV_DOG_COLOR_MAPPING = {
    "Apricot": "Apricot / Beige",
    "Beige": "Apricot / Beige",
    "Black": "Black",
    "Blond": "Yellow / Tan / Blond / Fawn",
    "Blue": "Gray / Blue / Silver",
    "Blue Black": "Black",
    "Brindle": "Brindle",
    "Brown": "Brown / Chocolate",
    "Chocolate": "Brown / Chocolate",
    "Cream": "White / Cream",
    "Fawn": "Yellow / Tan / Blond / Fawn",
    "Golden": "Golden",
    "Grey": "Gray / Blue / Silver",
    "Red/Mahogany": "Red / Chestnut / Orange",
    "Sable": "Sable",
    "Sandy": "White / Cream",
    "Silver": "Gray / Blue / Silver",
    "Tan": "Yellow / Tan / Blond / Fawn",
    "Wheaten": "Yellow / Tan / Blond / Fawn",
    "White": "White / Cream",
    "Yellow": "Yellow / Tan / Blond / Fawn",
}
