[project]
name = "sync_to_rescue_groups"
version = "0.1.0"
dependencies = ["requests"]
readme = "README.md"
authors = [
    { name = "Katie Patterson", email = "kpatterson67@gmail.com" }
]
requires-python = "==3.9.*"
